#ifndef GAME_STATE_H
#define GAME_STATE_H

typedef enum { 
    ESTADO_TITULO,
    ESTADO_MENU, 
    ESTADO_FARMEO,
    ESTADO_MINA,      
    ESTADO_TALLER, 
    ESTADO_GALERIA, 
    ESTADO_SELECTOR, 
    ESTADO_VIAJAR,
    ESTADO_TIENDA,
    ESTADO_CAJAS
} EstadoJuego;

#endif
